/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Bike } from "./Bike";
import { BikeCountArgs } from "./BikeCountArgs";
import { BikeFindManyArgs } from "./BikeFindManyArgs";
import { BikeFindUniqueArgs } from "./BikeFindUniqueArgs";
import { DeleteBikeArgs } from "./DeleteBikeArgs";
import { BikeService } from "../bike.service";
@graphql.Resolver(() => Bike)
export class BikeResolverBase {
  constructor(protected readonly service: BikeService) {}

  async _bikesMeta(
    @graphql.Args() args: BikeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Bike])
  async bikes(@graphql.Args() args: BikeFindManyArgs): Promise<Bike[]> {
    return this.service.bikes(args);
  }

  @graphql.Query(() => Bike, { nullable: true })
  async bike(@graphql.Args() args: BikeFindUniqueArgs): Promise<Bike | null> {
    const result = await this.service.bike(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Bike)
  async deleteBike(@graphql.Args() args: DeleteBikeArgs): Promise<Bike | null> {
    try {
      return await this.service.deleteBike(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
